#Spring:
#  datasource:
#    URL:
#    username:
#    Password:
#  jpa:
#    show-sql:
#    properties:
#      hibernate:
#        dialect:
#    hibernate:
#spring:
#  datasource:
#    driver-class-name = com.mysql.cj.jdbc.Driver
#    url: ${db_url}
#    username: ${db_user}
#    password: ${db_pass}
#
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update