logging:
  level:
    com:
      org: TRACE
    root: INFO
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${db_pass}
    url: ${db_url}
    username: ${db_user}
  jpa:
    hibernate:
      ddl-auto: update
